version: '3'
networks:
  ui-network:

services:
  api-service:
    container_name: api
    restart: always
    build: ../github-trending-api/.
    ports:
      - 8000:8888    # original port : destination port
    networks:
      - ui-network
  ui-service:
    container_name: ui
    restart: always
    build: .
    ports:
      - 8080:8080     # original port : destination port
    networks:
      - ui-network
  nginx-service:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443 # original port : destination port
    networks:
      - ui-network